### ISSUE TITLE
Wondering if can be used with jwiegley/alert

### ISSUE THREAD

**Issue by vmiheer** [gkowzan/alert-toast#2]
The specification is defined in: https://github.com/jwiegley/alert#builtin-alert-styles
That way it can also hook into https://github.com/spegoraro/org-alert.

**Comment by gkowzan** [comment]
Yes, the package defines a new alert style for jwiegley/alert.el. After you `(require 'alert-toast)`, you can set it as default alert style with `(setq alert-default-style 'toast)`, or use it in any way you would use one of the [builtin alert styles](https://github.com/jwiegley/alert#builtin-alert-styles).

**Comment by deb75** [comment]
It is not enough for `alert` to use `alert-toast` because as far as I read, the `toast` alert style is not defined in this package.

Putting this in your configuration file : 
```
(require 'alert-toast)
(require 'alert)

(alert-define-style 'toast :title "Windows 10 toast notifications"
                    :notifier #'alert-toast-notify)

(setq alert-default-style 'toast)
```

and the following works : 
```
(alert "This is an alert" :title "My Alert")
```

Regards

**Comment by gkowzan** [comment]
It is defined: https://github.com/gkowzan/alert-toast/blob/9b34b05650967f24a8b980e886612df52246779f/alert-toast.el#L286

**Comment by deb75** [comment]
My apologies, my comment was based on a `alert-toast` fork, in which it was actually gone.

Sorry again for that

Regards
