### ISSUE TITLE
Melpa

### ISSUE THREAD

**Issue by technician77** [gkowzan/alert-toast#3]
Thanks for this great package, but could you register your package in the Melpa repository?

As one of the few people who use emacs on Windows I really appreciate this package. It works great, but manual installation and updating is a hassle. Registering it on Melpa would also make the package more visible to new users.

**Comment by gkowzan** [comment]
Thanks, I'll try to get it done this week and update installation instructions when the package gets approved.

**Comment by technician77** [comment]
It's now up on Melpa. Great, thanks for the effort. You might want to update the readme regarding the installation.

**Comment by gkowzan** [comment]
You beat me to it. ;) Sorry that it took a while. I updated the readme.
